name: Build Branch

on: [push, pull_request]

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10.0"
          architecture: x64
      - name: Lint Code Base
        uses: psf/black@stable
        with:
          args: ". --check"
